<?php



$posts = [

       "post-main"=>"Megosztja a fejlesztési elképzelésekkel közvetlenül érintett lakosságot a Kossuth utcai (történelmi városközpont) területén megvalósítandó, mintegy kétharmad milliárdos projektötlet várható következményei. A mozi felújítás, a Szalkai-ház renoválása és ott villamossági és babamúzeum kialakítás, sétálóutcává való átalakítás csökkentett, egyirányú forgalommal, zöldövezettel, játszótérrel és a fény városát szimbolizáló köztéri elemekkel. A vita nem a megvalósítandó fejlesztésekről - amelyek jelentős része még a tervezés fázisában van - hanem a közvetlen lakókörnyezetre gyakorolt, vélt negatív következményeiről szól.",

      "post-content" => "A város első, alapos rendezési tervét Szokolay Örs és munkatársai készítették el. Még ma is ez a terv képezi a városfejlesztés alapjait. A terv foglalkozik a Kossuth utca, mint történelmi városközpont értékeinek megóvásával, részbeni visszaállításával. Építési korlátozásokat ír elő, illetve szorgalmazza a legjelentősebb épületek (zsinagóga, volt Almer patika, stb.) helyreállítását, az utcakép megőrzését, az orsó alakú valamikori piactér újbóli kialakítását. 1990 előtt az elképzelt utcakép megvalósításában nem sok előrelépés történt. A város vezetése sikertelen tárgyalást folytatott a MAZSIHISZ-szal, a zsinagóga tulajdonosával az épület átadásáról, vagy általa az épületveszély elhárításáról. Az utcában lévő lakások tulajdonosai is inkább az épületeik lebontását, semmint felújítását szerették volna elérni. Időközben két esemény tovább bonyolította az utca helyzetét.
    1988-ban a TITÁSZ helyi igazgatósága, Szilágyi Béla igazgató és munkatársai egy kiadványt állítottak össze a Trianon utáni Magyarország területén, Mátészalka településen elsőként megvalósuló köztéri elektromos világítás történetéről, 100 éves évfordulójáról. Az esemény alkalmából kiállítást rendeztek, felállították a Mécsestartó fiú köztéri szobrot, valamint emléktáblát helyeztek el a Szalkai-házon, valamint az egyetlen megmaradt, Kossuth utcai villamos kandelábernél.(A mátészalkai szeszgyár tulajdonosa 1888-ban, a párizsi világkiállításon látott áramfejlesztő generátort vásárolt az üzemébe. Onnan a legrövidebb úton a lakásába is elvezette az áramot, és a villanyoszlopokra világító testeket helyezett el.)",

      "post-content01" =>"A 80-as évek második felében a magyarországi zsidó hitközség által meghívott Tony Curtis két alkalommal is néhány órás látogatást tett Mátészalkán. Ellátogatott a zsidó temetőbe, a zsinagógába és részt vett a múzeum udvarán tartott vendéglátáson. A tanácsházán tartott rövid fogadásán felajánlotta, hogy elküldi majd egyik festményét, amelyet értékesítve hozzájárul a zsinagóga felújításának költségeihez.
      E két esemény utólagosan lassan módosította a Kossuth utcáról korábban tervezett elképzeléseket. Mátészalka, mint a „fény városa”, valamint a „Hollywood bölcsője” szóképek születtek, amely metaforák lassan uralták a közbeszédet. A rendszerváltozás utáni városvezetés e két jelenségre építette a város arculatát, vonzerejének növelését. A Kossuth utcai épületek szomorú sorsa tovább folytatódott. Bár az időközben életveszélyessé vált zsinagóga összeomlását sikerült megakadályozni, több várostörténeti és utcaképi jelentőségű épületet életveszélyesnek nyilvánítva lebontottak, és helyükre többszintes társasházakat építettek, vagy foghíjként éktelenkednek. Néhány régi épületet magánszemélyek megvásároltak és az eredeti elképzelések szerint felújítottak. Ma ezek az utca legszebb hagyományőrző épületei. A forgalom növekedésével eltűntek a gömbakác fasorok, a bazaltkockás út, s lett széles aszfaltút, sok parkoló és maradtak a korábban ültetett platánfák.",

       "post-content02" => "A kormány az elmúlt években jelentősen átalakította az EU-s pénzek elnyerésére szolgáló pályázati előírásokat. Azért, hogy könnyebben hozzá lehessen jutni, s egyben a választásokig kiossza a teljes, - rengeteg pénzt tartalmazó – keretet, elég volt egy részletesebb projektötletet beadni, becsült költségekkel. (Néhány kormány közeli személy, vagy képviselő milliárdos keretekről beszélt, amellyel ő rendelkezik.) A projekt részletes kimunkálása, az engedélyes és kiviteli tervek, költségvetés elkészítése csak később került sorra. A város is így nyert el több projektet, melynek kidolgozása most történik. Ezért semmi különös nincs abban, hogy a lakosság körében téves információk keringtek a megvalósítandó fejlesztésekről az ötletelések idején.
       Az EU előírása, hogy a projekt megvalósítása a nyilvánosság kötelező alkalmazása, közösségi programok esetén pedig a lakosság bevonásával történjen. Feltételezve, hogy a város vezetése e nélkül is a lakossággal együttműködve végezte volna a kidolgozást, nem kerülheti el az érintettek bevonását.",

       "post-content03" => "  A nyertes projektek egy részének megvalósítása a kivitelezés (mozi), másik része a tervezés fázisában van. Szinte mindenki egyetért azzal – ha már az EU és a kormány a teljes költséget fedezi -, hogy legyen korszerű filmszínház, világítási-, és babamúzeum. A Kossuth utca gépjárműforgalmának drasztikus csökkentése, a parkolóhelyek áthelyezése, az ott lévő intézmények és lakások megközelítése, kiszolgálása, lehetséges megoldási módja azonban félelemmel tölti el a környezetében lakókat. Szerintük az élethelyzetük romlását fogja eredményezni, ezért heves ellenállást vált ki a fejlesztés megvalósítása. A szinte tiltakozássá fajult ellenzés az Alkotmány út keleti oldalán lakó mintegy négyszáz család többségénél tapasztalható. A négysávos út zaja, egészségkárosító kipufogó gázai megakadályozzák a szellőzés, ablaknyítás lehetőségét. Az épületsor keleti oldalán található tömbbelső több évtizedes elhanyagoltsága (befejezetlensége) már most is komoly feszültséget okoz. Itt kellene megteremteni a lakosságszámhoz szükséges zöldterületeket, parkolókat, játszótereket. Ez a terület erre a célra már most is kevés. Még akkor is kevés lesz, ha 5-10 éven belül megépül az M49-es autóút, és az Alkotmány út két külső sávjában parkolni lehet. A városvezetés jelenlegi elképzelése szerint a Kossuth utca parkolóhelyei többsége a tömbbelsőben kerülnek elhelyezésre, és a nyugati oldalán lakók gépjármű ki-be közlekedése, szolgáltatásai (szemétszállítás, stb.) ellátása is innen történik. A fejlesztendő területen lévő köz-, és kulturális intézmények (bíróság, múzeum, mozi) látogatóinak gépjárművel érkező többsége is innen tudja megközelíteni. Más jellegű, de hasonló félelmek fogalmazódnak meg a Munkácsi és a Dózsa utcai lakosok egy részében.",

       "post-content04" => "Alapszabály a várostervezésben, hogy bármilyen fejlesztést komplexen kell kezelni. Meg kell vizsgálni annak beilleszthetőségét, környezetére gyakorolt hatását. Száz lakos élethelyzetét javító, ingatlanja értékét jelentősen növelő fejlesztés nem eredményezheti ezer másik lakos életkörülményeinek romlását. Vizsgálni kell, hogy a köz-, és kulturális intézmények várt jentős látogatószám növekedése hogyan oldható meg optimálisan.",

       "post-content05" => "-	meg kell vizsgálni a Kossuth utca lakóházait, hasonló részletességgel, mint az ott lévő fákkal, bokrokkal elvégezték. El kell dönteni, mi lesz a sorsuk, melyik kerül felújításra, melyik lebontásra és helyén új építése, vagy átjáró kialakítása a tömbbelsők felől. Ne feledjük, a fejlesztést követően jelentősen megnőnek az ingatlanok értékei. Megéri mind felújítani, mind újat építeni a befektetőknek. Nem szerencsés az sem, ha a díszburkolatok, parkok, köztéri létesítmények elkészítését követően kerül sor jelentős építkezésekre, mert az csak a tömbbelső felől történhet.",
       "post-content06" => "-	a Kossuth utca - fejlesztéssel érintett - területét együtt kell kezelni az Alkotmány úti tömbbelsővel. Tömbrehabilitálással, a két terület átjárókkal való összenyitásával elérhető, hogy az Alkotmány úton lakók is magukénak érezzék a területet. A gyerekes családok és az idősek pihenőövezete, játszótere, a fiatalok fóruma lehet. Ugyanakkor meg kell tiltani a tömbbelsőben a gépjármű átjáró forgalmat.",

       "post-content07" => "-	a Kossuth utca keleti oldala (a zsinagóga és a Szilágyi ház) mögötti tömbbelső hogyan vonható be parkolóhelyek és akár garázsok elhelyezésére. Innen sokkal könnyebben megközelíthető lenne a mozi és a bíróság. Itt is van lehetőség a foghíjak felhasználására esztétikus, praktikus átjárók kialakításához. Talán lehetőség kínálkozik az Alkotmány úton lakók gépjárműveinek elhelyezésére is.",

         "post-content08" => "-  a Dózsa György utca összekötése a Rákóczi utcával a katolikus templom és az alapfokú oktatási intézmény mögött. Ezzel be lehetne vonni a fejlesztési területbe a két templomot, a múzeumot, az oktatási intézményt és a katolikus közösségi házat is. Jó gondolat a tervezők részéről, hogy a fürdő régi bejárata mögött helyezzenek el lehetőleg minél több parkolót. A lakópark bejáratát is át kell helyezni.",
         "post-content09" => "Az általam ismertetettek kötelező és szükségszerű lépései a városfejlesztő munkáknak. Ezek a többletmunkák persze többletköltséget is jelenthetnek. De ha volt forrás a jó állapotú közvilágításunk jobbra cserélésére, erre is biztosítható. Van még EU-s lehetőség, amely kiegészíthető városi pénzekkel. A város vezetése és az országgyűlési képviselő ennek megszerzésére törekedjen. Ebben az évben önkormányzati választások lesznek. Ha nem akarjuk, hogy viták, civakodások, tüntetések kísérjék a választási kampányt, ha a városvezetés szeretné megőrizni pozícióit, jól teszi, ha meghallja a lakosság véleményét és elvárásainak igyekszik megfelelni. A város a lakosaié."


];

$post = [

       "post-main"=>"A múlt század 60-as éveiben kormányhatározat született a vidéki iparfejlesztésről. Ennek keretében, döntően budapesti cégek kitelepítésével, Mátészalkán is látványos ipartelepítés történt. Első lépésként kialakításra került az ipari zóna, ahová zöldmezős beruházásként felépítésre került a MOM, a Bfk, a Bútorgyár, illetve közelükbe az ISG, valamint a Tejporgyár. Rövid időn belül a hagyományosan élelmiszer és fafeldolgozáson alapuló iparszerkezet jelentős átalakuláson ment keresztül.",

      "post-content" => "A gazdaság fejlődése az ezt követő időszakban is intenzíven történt. Az elkészített városfejlesztési és rendezési tervek alapján, a két évtized alatt megduplázódó lakosság számát 2025-re 35 ezer főre prognosztizálták. A 80-as évek elejétől kezdődő időszakban erre a lakosságszámra való figyelemmel indult meg a kiszolgáló intézményrendszer (oktatási, szakképzési, egészségügyi, kulturális, államigazgatási) és infrastruktúra (posta és távközlési, közlekedési, energetikai) megteremtése és bővítése. A gazdaság fejlődése megkövetelte, de egyben lehetővé is tette a város példátlan fejlődését. Ugyanakkor a város modernizálódása további húzóhatást jelentett a gazdaság fejlődésére. Mátészalka város vezetése ebben az időszakban jól biztosította a gazdaság és a városfejlesztés közötti kívánatos egyensúlyt. A gazdaság töretlen fejlődését biztosította a színvonalas és elegendő szakképzés, a közlekedési és egyéb infrastruktúra megléte, valamint a bőségesen rendelkezésre álló munkaerő.",

      "post-content01" =>"Az 1990-ben bekövetkezett rendszerváltozás komoly átrendeződést eredményezett. A volt szocialista országok versenyképtelenné váltak a kinyíló világpiacokon. Exportlehetőségeik csökkentek, azon belül pedig a meghatározó szovjet-orosz piacot – annak fizetőképtelensége miatt – szinte teljesen elveszítették. Ez a változás a mátészalkai üzemeket is súlyosan érintette. A 90-es évek elején az ipari munkahelyek közel 70%-a megszűnt. A csökkenő jövedelmek súlyos csapást jelentettek a városi szolgáltató és kereskedelmi kisvállalkozásokra is. A munkaerő jelentős része elhagyta a várost, vagy rokkantsági nyugdíjba menekült. Bezárt a Bfk, az Erdért, a SzÁTG, a Húsüzem, drasztikusan csökkent a foglalkoztatottak száma a MOM-nál, a Bútorgyárnál, az ISG-nél, a Tejporgyárnál és az építőipari cégeknél.",

       "post-content02" => "Az elmozdulást a privatizáció hozta meg. A legsikeresebb formáját a MOM szolgáltatta. Mivel a budapesti központ ingatlanspekuláció áldozata lett, az üzem második világháború előtti tulajdonosa a Carl Zeiss figyelme a legnagyobb vidéki gyáregysége felé irányult. Mátészalka szerencsés helyzetben volt abban a vonatkozásban is, hogy ide települt a vízmérőgyártás, fékrendszerek gyártása és a fegyvergyártás (finommechanika), valamint a szemüveglencse gyártás és bizonyos síkoptikai termékek gyártása (optika). A Carl Zeiss kivásárolta az üveg szemüveglencse gyártó üzemet. A műanyaglencse gyártó üzemet a belga Buchman cég vásárolta meg, majd röviddel később a japán HOYA tulajdonába került. A vízmérőgyártó üzemet az osztrák Elin Wassertechnik cég privatizálta, majd rövidesen továbbadta a német Dill cégnek, melynek Hidrometer vállalatcsoportjához került. Rövidebb átmenet után sikeres privatizáció történt a „túró rudi” terméket magának tudó tejüzemnél is.",

       "post-content03" => "Az optikai ágazat privatizálása Mátészalka gazdaságának sikertörténete a 90-es években. A tőkeerős, versenyképes termékeket birtokló külföldi nagyvállalatok az olcsó, bőségesen rendelkezésre álló szakképzett munkaerőre támaszkodva jelentős fejlesztéseket hajtottak végre. A Zeiss egymás után építette meg új zöldmezős üzemeit, a műanyaglencse üzemét, az optikai felületkezelő üzemét, a finomoptikai és finommechanikai üzemét (távcsőüzem), és az autótükör gyártó üzemét (Schott Desag, majd Flabeg). a HOYA is új üzemet épített, ahol a szériagyártást rövidesen felváltotta a nagyobb hozzáadott értéket jelentő multifokális lencsék gyártása. Mátészalka közép-Európa legnagyobb szemüveggyártó központjává vált. Ennek köszönhető, hogy Mátészalkát választotta gyártóhelyéül a G&B síkoptikai és a SpeckSavers angol cég Szatmár Optika szemüvegkészítő gyára. Ezzel egyidejűleg megsokszorozódott a foglalkoztatottak száma is.",

       "post-content04" => "A „túró rudi” közkedveltsége, tartós piaci helyzete, tőkeerős külföldi tulajdonosa szintén biztosíték volt a vállalat stabil működésére és fejlődésére. A magyar tulajdonba került üzemek sorsa azonban nem ilyen szerencsésen alakult. Tőkehiányuk és korszerűtlen termékszerkezetük miatt fejlődésük elmaradt, a foglalkoztatottak száma folyamatosan csökkent. Többüknek a fennmaradása is kérdéses. Ritka kivételt képez a kiváló gyümölcsalapanyagot feldolgozó, folyamatos termékkínálattal jelentkező Nobilis Zrt.",

       "post-content05" => "A rendszerváltás után folyamatosan csökkent az együttműködés erőssége a város vezetése és a vállatok között. A vállalatok vezetői kezdetben még többnyire a korábbi helyi vezetők voltak, azonban megjelentek mellettük a tulajdonosok külföldi, vagy máshonnan jövő menedzserei, akik csak a tulajdonos elvárásaira figyeltek és minimális lokálpatriotizmust éreztek a város iránt. Bár a privatizáció során a város tulajdonrészt szerzett valamennyi vállalatnál a telekérték arányában, azt saját szűkös forrásaik pótlása érdekében viszonylag gyorsan el is adták. A megmaradó együttműködés példájaként az Ipari Park cím elnyeréséért benyújtott közös pályázat említhető.",

       "post-content06" => "Folyamatosan megszűntek ugyanakkor azok az együttműködési formák, amelyek korábban a gazdaságfejlesztés hajtóerői voltak. Folyamatosan gyengült a szakképzés színvonala. Sem a tananyag, sem a gyakorlati képzés tárgyi feltételei, sem az oktatók képzettsége nem felelt meg a vállalatok elvárásainak. A Zeiss, miután használhatatlannak találta az állami képzés eredményét már a 90-es évek második felében kialakította saját képzőbázisát, ahol német tananyaggal, Németországból áttelepített tanműhelyben, saját oktatók alkalmazásával végezte a képzést. Bár a tanulók állami intézményben is kaptak elméleti képzést, annak szakmai része használhatatlan volt. (Duális képzés). A szakképzés színvonalát tovább gyengítette, hogy folyamatosan felszámolásra kerültek a korábban évtizedekig jól működő vállalati gyakorlati képzőhelyek, ahonnan a gyakorlati képzés is az állami intézménybe került, a szükséges feltételek biztosítása nélkül.",

       "post-content07" => "További problémaként jelentkezett a szakképzésre jelentkezők gyengülő képessége, alapismereteik szintje. Még az érettségit is adó szakközépiskolákban végzettek tudása is lassan használhatatlanná vált. Az újonnan megjelenő, „futószalagon”termelt, felnőtt szakképzési formák többnyire alkalmatlanok voltak komolyabb szakismeret elsajátítására. A város - anyagi forrás hiányában is - alig fordított figyelmet a vállalatok igényeinek felmérésére (infrastruktúra, szakképzés, átképzés, közlekedés, államigazgatás, stb.) Ezek a támogatások pedig egyre inkább szükségessé váltak. Kezdetben ugyanis a multinacionális cégek az olcsó munkaerőre számítva az alacsony hozzáadott értékű szériagyártásukat telepítették át.",

         "post-content08" => "Idővel azonban ezeknek a termékeknek olcsóbb területeket találtak (India, Mexikó, Kína, stb.), s a helyükre jöhető bonyolultabb termékek (multifokális lencsék, távcsövek, hőmennyiségmérők, stb.) jobb képzettséget és infrastruktúrát követeltek meg. A város vezetése részéről 2006-tól számolva egy erősen politikai érdekkel kísért elzárkózás alakult ki. Pedig a meghatározó üzemek (Zeiss, HOYA, MOM) több évtizede a városban élő és dolgozó vezetői részéről több olyan kezdeményezés indult, amely biztosította volna az élmezőnyben maradást és a folyamatos fejlődést.",
         "post-content09" => "a 90-es évek elején mátészalkai vállalkozások vezetői megalapították érdekvédelmi szervezetüket, a Mátészalkai Munkaadók Szövetségét, amely folyamatosan bővülve megyei vállalkozásokkal rövidesen a Kelet-Magyarországi Munkaadók Szövetségévé (KMSz) alakult át. A szövetség az MGYOSZ Sz-Sz-B megyei tagszervezeteként jól képviselte tagjai gazdasági érdekeit. Több vállalati vezető helyet foglalt a megyei Kereskedelmi és Iparkamara, valamint a megyei és regionális Fejlesztési Tanácsok vezetésében és munkájában. Brüsszelben területfejlesztési mintaprogramot mutattak be.",

         "post-content10" => "Létrehozták a Szatmári Gazdaságfejlesztési Alapítványt. Az alapítvány jelentős vállalati és magán hozzájárulással, határon átnyúló program keretében elkészítette gazdaságfejlesztési programját és megépítette a mátészalkai Inkubátorház és Képzési Központot. A város akkori képviselő testülete a vállalatokhoz hasonlóan támogatást nyújtott (amit egy későbbi vezetés visszakért), majd a következő testület a beruházáshoz területet biztosított tartós használati joggal. Az inkubátorház helyet adott több induló kisvállalkozásnak, itt tanították be a Szatmár Optika induló létszámát. A HOYA ugrásszerű bővítéséhez is segítséget nyújtott.",

         "post-content11" => "A felnőttképzés meghatározó bázisa lett. Megalapították az Optomechatronikai Klasztert, amelynek munkájában, célkitűzései megvalósításában részt vett a térségünkből származó, középiskoláját Mátészalkán végző, a Műegyetem szenátusának tagja, Fodor István és az Optomechatronikai Tanszék vezetője Ábrahám György, aki az alapítvány kuratóriumának is tagja lett. Mivel Budapesten a MOM megszűnésével már nem volt számottevő optikai üzem az egyetem nehéz helyzetbe került a hallgatók gyakorlati képzésének biztosításával, kutatási munkájuk végzésével. Mátészalkán, a világ két leghíresebb optikai üzemében megteremtődtek azok a műszaki és technológiai feltételek ahol hallgatóik és kutatóik munkájukat végezhetnék.",
        "post-content12" => "Az együttműködésük céljaként kihelyezett optomechatronikai képzés létesül Mátészalkán a felújított Baross Gábor szakközépiskola helyiségében, valamint az inkubátorházban kialakított optikai és finommechanikai tanműhelyekben. A gyakorlati képzőhelyeket a budapesti hallgatók és kutatók is használhatnák. Kimunkálják és elvégzik az optikai és finommechanikai területen kis-, és középvezetői szinten dolgozó szakemberek képzettségi szintjének emelését. Fodor István segítséget ígért középiskolájának, az Esze Tamás Gimnáziumnak is, hogy jelentősen javíthassa képzési feltételeit. A Zeiss vezetője megszervezte, hogy a Műegyetem, a Miskolci Egyetem, a Debreceni Egyetem és a Nyíregyházi Főiskola szakirányú oktatói és kutatói tanulmányúton ismerjék meg Németországban a leghíresebb optikai, finommechanikai üzemek munkáját, a szak elméleti és gyakorlati képzését.",

        "post-content13" => "E látogatás is hozzájárult ahhoz, hogy a Zeiss központ, Oberkochen város polgármestere testvérvárosi kapcsolat kialakítását kezdeményezte a várossal. A képzési anyag elkészült, az oktatási anyag leadásra került a kis és középvezetők részére. Azonban a további elképzelések megvalósítása megbicsaklott az új polgármester és képviselő testület különös hozzáállásán.",

        "post-content14" => "Mivel a két legnagyobb optikai üzemünk egyúttal versenytársa is volt egymásnak, megállapodás született köztük, hogy a gyakorlati képzést a Zeisstől semleges helyre, az inkubátorházba telepítik át, ott kialakítva az általuk biztosított legmodernebb berendezésekkel az új gyakorlati képzési helyeiket. Az önkormányzat azonban nem járult hozzá, hogy az optikai üvegcsiszoló, valamint a mechatronikai gyakorlati képzés ott valósuljon meg. Az alapítvány kidolgozta és elkészítette az inkubátorház második és harmadik ütemének fejlesztését és pályázati anyagát, de az önkormányzat kérte, hogy mivel neki nincs tulajdonrésze az inkubátorházban, ezt a fejlesztést az ő neve alatt valósítsák meg. Az alapítvány átadta a pályázati anyagot és az építési engedélyt, de a kétütemű pályázati eljárás második fordulójában az önkormányzat a pályázatot nem nyújtotta be és az építési engedélyt annak lejártáig (5 év) nem adta vissza.",

        "post-content15" => "Az alapítvány további együttműködési szándékának kifejezéseként ellentételezés nélkül visszaadta a városnak több tízmillió forint értékű területét azzal a feltétellel, hogy ott épül meg az új autótükör gyártó üzem. A munkaadók szövetsége minden évben egyeztető megbeszélésre hívta meg a város polgármesterét és képviselő testületét, azonban ezeken a találkozókon sem a polgármester, sem a kormánypárti képviselők soha nem jelentek meg. Az Inkubátorházat „kommunista fészek”- ként aposztrofálták, mivel a három legnagyobb üzem vezetője, az alapítvány munkáját leginkább segítők, a szocialista időszakban is vezetők voltak már.",

        "post-content16" => "Az együttműködés olyan mélységbe került, hogy amikor a repülőgép részegységeket gyártó, a városban letelepedni szándékozó Dill Aircabin cég képviselőit egy korábbi cégvezető, a munkaadók szövetségének elnöke a város vezetőinek be kívánt mutatni és tárgyalni a letelepedésről a polgármester, majd a jegyző is más irányú elfoglaltsága miatt elzárkózott a fogadástól. Nyírbátor városa kapva kapott a váratlan lehetőségen, és ott valósult meg a ma már egyre impozánsabb beruházás.",
        "post-content17" => "Az önkormányzat és a gazdasági szereplők viszonya az elmúlt időszakban javult, azonban időközben elvesztek azok a lehetőségek, eltávoztak azok a személyek, amelyek erős lokálpatrióták lévén a város érdekeit tartották szem előtt. Megszűnt az Optomechatronikai Klaszter, felbomlott a munkaadók szövetsége, eltávoztak a mátészalkai kötődésű, lokálpatrióta vezetők, leépültek a kapcsolatok a segíteni és együttműködni tudó intézményekkel és személyekkel. A város ipar-, és gazdaságfejlesztése mélypontra került. Az újraépítő szándékok eddig vérszegény eredményt mutatnak.",
        "post-content18" => "A város jelenlegi vezetése igyekszik látványosan javítani a kapcsolatot a gazdaság szereplőivel (évente két alkalommal, vacsorával egybekötött beszélgetés, díjak adományozása, stb.), de a körülmények jelentősen megváltoztak és a hozzáértő szakemberek is hiányoznak. Gyakori a vezetőcsere, esetenként zűrös vezetőváltások történnek. Bár az iparűzési adóbevétel folyamatosan növekszik, az nem jelenti a gazdaság fejlődését. A városban működő, jelentősebb árbevételt elérő, és nagyszámú munkaerőt alkalmazó vállalatok az olcsó munkaerőre támaszkodnak.",
        "post-content19" => "Ez a munkaerő egyre kevesebb, és képzettsége egyre alacsonyabb az újonnan belépők által. A szakképzett munkaerő egyre nagyobb része külföldre távozik, pótlásuk a jelenlegi bérszínvonalon lassan megoldhatatlan. Egymástól rabolják el a munkaerőt, vagy külföldről próbálják azt biztosítani. A vállalatok jelenlegi termékszerkezete többnyire betanított munkást igényel. A bérszínvonal további növekedésével fennáll a veszély a gyártásuk kitelepítésére. A szakképzés színvonalát sem sikerült érdemben javítani, a kapkodó változtatások még rosszabb helyzetet eredményeztek. Tudományos és Technológiai Park címet nyert el a város, miközben az utolsó helyi vállalatnál, a MOM-nál is megszűnt a fejlesztési részleg.",

        "post-content20" => "Az együttműködést pedig nem az optikai, optomechatronikai képzésben jártas egyetemekkel, hanem az ebben a szakmában teljesen járatlan Nyíregyházi Egyetemmel képzeli el. Második inkubátorházat készül építeni, amely tulajdonképpen egy üres gyártócsarnok (amelyet majd felajánlhatnak egy betelepülni szándékozó cégnek), ahelyett hogy a már meglévő inkubátorhoz csatlakozva, annak tapasztalatát és lehetőségét kihasználva azt bővítve teremtené meg az innováció és K+F feltételeit. Furcsa fintora a helyzetnek, hogy az elmúlt időszakban betelepülő egyetlen, 10 főnél többet foglalkoztató cég tevékenysége az EU-s támogatásból vásárolt drága terepjárók luxus kiegészítőkkel való felszerelése. (Ez a pénz hatékonyabb lenne, ha a gazdák technológiai fejlesztésre fordítanák, ezáltal versenyképességüket növelnék.)",
        "post-content21" => "Ha a város gazdasága nem tudja versenyképességét fenntartani, a 90-es évekhez hasonló visszaesés várható a szolgáltató és kereskedelmi kisvállalkozásoknál is. Az önkormányzat és intézményrendszere is nehéz helyzetbe kerül. A mára már a 16 ezer főt alig meghaladó lakosságszám tovább csökkenhet. Sürgős, hozzáértő változásra van szükség. A városnak megvannak a személyi és tárgyi feltételei. Csak az önkormányzati vezetés szelektíven választja ki azokat. A politikai (nem várospolitikai) szempontok érvényesítése kizárja a hozzáértők együttműködési hajlandóságát, a felhalmozott ismeretek és tudás összehangolását.",
        "post-content22" => "Nem szükséges teljesen új dolgokat kitalálni, csupán a meglévő adottságainkat és lehetőségeinket kell felerősíteni. A város gazdaságát a finommechanikai, optikai, optomechatronikai ágazat dominálja. Emellett megvannak az alapjai és hagyományai az élelmiszer feldolgozásnak is. Ezekre építve kell megerősíteni és újjászervezni a tanuló és felnőtt szakképzést, a gazdasági infrastruktúrafejlesztést, a helyi és térségi közlekedés módosítását.",
        "post-content23" => "Élhetőbbé kell tenni a várost az itt élő emberek számára, javítva az egészségügyi ellátást, a szociális ellátórendszert, az alapinfrastruktúrák (út, járda, csapadékvíz elvezetés, lakótelepi tömbbelsők, stb.) színvonalát. Támogatni kellene a Mátészalkán nagyszámú kényszer-kisvállalkozások megerősítését. A korábbi évtizedekben kiépült gazdaság szereplői által befizetett helyi adók még biztosítják a fentiekhez szükséges forrásokat. Azokat célirányosan kell felhasználni, mert ellenkező esetben, megújulás hiányában folyamatosan csökkenni fognak a város bevételei.",
        "post-content24" => "Mátészalka gazdaságát újra arra a pályára kell állítani, amelyen a 60-as években elindult. Sokan vannak, akik ebben részt akarnak, és tudnak vállalni."
];
